# Use official Node.js image as base
FROM node:latest

# Set working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY settings-template.json settings.json

# Command to run script
CMD ["node", "src/scripts/bazaarWatcher.js"]
